version: '3'

services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '8080:80'

    volumes:
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './config/nginx/conf.d:/etc/nginx/conf.d/'
      - './htdocs:/var/www/html'

  php-fpm:
    image: 'php:7.4-fpm'

    volumes:
      - './htdocs:/var/www/html'
      - './config/php:/usr/local/etc/php/conf.d'
      # - './config/php-fpm:/usr/local/etc/php-fpm.d/'
      - './tmp/xdebug:/tmp/xdebug'

  mysql:
    image: 'mysql:8.0'

    ports:
      - '3306:3306'

    volumes:
      - './config/mysql:/etc/mysql/conf.d'
      - './htdocs:/var/www/html'

    environment:
      MYSQL_ROOT_PASSWORD: mysql-root